name: CI - Deployment Games Vault

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: dist
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Node.js with Yarn cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build UI package first
      - name: Build UI package
        run: yarn workspace @games-vault/gamesvault-ui build

      # Build front app
      - name: Build front app
        run: yarn workspace @games-vault/gamevault-front-app build

      # Build Storybook
      - name: Build Storybook
        run: yarn workspace @games-vault/gamesvault-ui build-storybook

      # Prepare deployment folder for GitHub Pages
      - name: Prepare deployment folder
        run: |
          mkdir -p dist
          cp -r apps/gamevault-front-app/dist/* dist/
          mkdir -p dist/storybook
          cp -r packages/gamesvault-ui/storybook-static/* dist/storybook

      # Upload the dist folder as artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site-dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Checkout is still needed
      - name: Checkout
        uses: actions/checkout@v4

      # Download the artifact from build job
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site-dist
          path: .

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload the site folder
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
