name: CI - Deployment Games Vault

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  contents: write  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Node.js with Yarn cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 1️⃣ Build UI package first
      - name: Build UI package
        run: yarn workspace @games-vault/gamesvault-ui build

      # 2️⃣ Build front app
      - name: Build front app
        run: yarn workspace @games-vault/gamevault-front-app build

      # 3️⃣ Build Storybook for UI package
      - name: Build Storybook
        run: yarn workspace @games-vault/gamesvault-ui build-storybook

      # Prepare deployment folder for GitHub Pages
      - name: Prepare deployment folder
        run: |
          mkdir -p dist
          cp -r apps/gamevault-front-app/dist dist/
          mv dist/dist dist/app
          cp -r packages/gamesvault-ui/storybook-static dist/storybook

      # Deploy combined build to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
